AWSTemplateFormatVersion: '2010-09-09'
Description: "CloudFormation template to spin up all necessary infrastructure for EMR and S3."

Resources:
  # Nested S3 Stack
  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: s3.yaml

  # Nested EMR Stack, which depends on the S3 bucket created in S3Stack
  EMRStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: emr.yaml
      Parameters:
        S3BucketName: !GetAtt S3Stack.Outputs.S3BucketName

Outputs:
  S3BucketName:
    Description: "The name of the S3 bucket for data and logs"
    Value: !GetAtt S3Stack.Outputs.S3BucketName

  EMRClusterId:
    Description: "The ID of the EMR cluster"
    Value: !GetAtt EMRStack.Outputs.EMRClusterId
