AWSTemplateFormatVersion: '2010-09-09'
Description: "CloudFormation template for batch processing and data analytics using Amazon EMR."

Parameters:
  InstanceType:
    Type: String
    Default: 'm5.xlarge'
  ReleaseLabel:
    Type: String
    Default: 'emr-7.0.0'
  # SubnetId:
  #   Type: String
  TerminationProtected:
    Type: String
    Default: 'false'
  ElasticMapReducePrincipal:
    Type: String
    Default: 'elasticmapreduce.amazonaws.com'
  Ec2Principal:
    Type: String
    Default: 'ec2.amazonaws.com'

Resources:
  # S3 Bucket for Raw and Transformed Data
  AnalyticsS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "data-platform-bucket-${AWS::AccountId}"
      VersioningConfiguration:
        Status: Enabled

  # EMR Cluster
  cluster:
    Type: AWS::EMR::Cluster
    Properties:
      Instances:
        MasterInstanceGroup:
          InstanceCount: 1
          InstanceType: !Ref InstanceType
          Market: ON_DEMAND
          Name: cfnMaster
        CoreInstanceGroup:
          InstanceCount: 1
          InstanceType: !Ref InstanceType
          Market: ON_DEMAND
          Name: cfnCore
        TaskInstanceGroups:
          - InstanceCount: 1
            InstanceType: !Ref InstanceType
            Market: ON_DEMAND
            Name: cfnTask-1
          - InstanceCount: 1
            InstanceType: !Ref InstanceType
            Market: ON_DEMAND
            Name: cfnTask-2
        TerminationProtected: !Ref TerminationProtected
        # Ec2SubnetId: !Ref SubnetId
      Name: CFNtest
      JobFlowRole: !Ref emrEc2InstanceProfile
      ServiceRole: !Ref emrRole
      ReleaseLabel: !Ref ReleaseLabel
      VisibleToAllUsers: true
      Applications:
        - Name: Spark
      LogUri: !Sub s3://${AnalyticsS3Bucket}/logs/
      Tags:
        - Key: key1
          Value: value1
  emrRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2008-10-17
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: !Ref ElasticMapReducePrincipal
            Action: 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonElasticMapReduceRole'
  emrEc2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2008-10-17
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: !Ref Ec2Principal
            Action: 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonElasticMapReduceforEC2Role'
  emrEc2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref emrEc2Role

Outputs:
  S3BucketName:
    Description: The name of the S3 bucket for data and logs
    Value: !Ref AnalyticsS3Bucket

  EMRClusterId:
    Description: The ID of the EMR cluster
    Value: !Ref cluster
